services:

  mongodb:
    image: mongo:8
    container_name: mongo-db-acal
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: acal
    volumes:
      - ./docker/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - acal

  #prometheus:
  #  image: prom/prometheus:latest
  #  container_name: prometheus
  #  volumes:
  #    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #  ports:
  #    - "9090:9090"
  #  depends_on:
  #    - mongodb
  #  networks:
  #    - acal

  #grafana:
  #  image: grafana/grafana:latest
  #  container_name: grafana
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - prometheus
  #  networks:
  #    - acal

networks:
  acal:
    driver: bridge


