spring:
  application.name: core

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/acal?authSource=admin
      auto-index-creation: true
      connection-pool:
        max-size: 100
        min-size: 0
        max-wait-time: 120000
        max-connection-life-time: 0
      socket:
        connect-timeout: 10000
        read-timeout: 10000

  jackson:
    property-naming-strategy: SNAKE_CASE

acal:
  version: 0.0.2-[water-quality]

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
    prometheus:
      enabled: true
    info:
      enabled: true

prices:
  water:
    free-tier: 1000.0
    price-per-unit: 0.004
