spring:
  application.name: core

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:example@localhost:27017/acal?authSource=admin}
      auto-index-creation: true
      connection-pool:
        max-size: 100
        min-size: 0
        max-wait-time: 120000
        max-connection-life-time: 0
      socket:
        connect-timeout: 10000
        read-timeout: 10000

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml

  jackson:
    property-naming-strategy: SNAKE_CASE
