spring:
  application.name: core

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/acal?directConnection=true
      auto-index-creation: true

  jackson:
    property-naming-strategy: SNAKE_CASE

